project:
  type: website
  output-dir: docs

website:
  title: "Home"
  navbar:
    left:
      - text: "Publication"
        file: publication.qmd

format:
  html:
    page-layout: full
    theme: flatly
    css: styles.css
    toc: true

editor: visual

